require('dvratil.plugins')
require('dvratil.general')
require('dvratil.mappings')

require('dvratil.plugins-nvim-tree')
require('dvratil.plugins-indent-blankline')
require('dvratil.plugins-telescope')
require('dvratil.plugins-bufferline')
require('dvratil.plugins-gitsigns')
require('dvratil.plugins-which-key')
require('dvratil.plugins-treesitter')
require('dvratil.plugins-lspconfig')
require('dvratil.plugins-cmp')
require('dvratil.plugins-nvim-ide')
require('dvratil.plugins-trouble')
--require('dvratil.plugins-zeal')
